[package]
name        = "zydis"
version     = "0.0.1"
authors     = ["Joel Höner <joel@zyantific.com>"]

description = "Bindings for Zydis"
license     = "MIT"
keywords    = ["disassembler"]
repository  = "https://github.com/zyantific/zydis-rs/"

build       = true

[build-dependencies]
gcc         = "0.3.53"
bindgen     = "0.29"
